bpf/lbr.c
internal/bpflbr/bpf_prog_flag.go
internal/bpflbr/bpf_tracing.go
internal/bpflbr/flags.go
internal/bpflbr/lbr_bpf_prog.go

1. Retrieve bpf progs of specified process by `-p pid:${pid}`.
2. Trace only for specified process by `--filter-pid ${pid}`.

Introduce two pid-related features

---

README.md
internal/bpflbr/bpf_tracing_info.go
internal/bpflbr/flags.go
internal/bpflbr/lbr.go
internal/bpflbr/lbr_stack.go

1. Remove deprecated `--dump-jited` option.
2. Ignore `ErrKeyNotExist` when fail to lookup `func_stacks` map.
3. Skip tracing bpf progs as they can't be traced.
4. Enhance output LBR/function stack when verbose and when not verbose.

Some misc updates

---

README.md
bpf/lbr.c
go.mod
go.sum
internal/bpflbr/bpf_tracing.go
internal/bpflbr/flags.go
internal/bpflbr/kernel_functions.go
main.go

Do some enhancements for kernel functions:
1. Filter kernel functions by shell wildcards way, like '*tcp_*rcv'.
2. Support tracing functions in kernel module.
3. Add 'ready' global variable to wait for user space being ready.

Filter kernel functions by shell wildcards way

---

internal/bpflbr/disasm.go
internal/bpflbr/flags.go

If `-B` is not provided, it will end early if meet `retq` or `int3` or limit to 4096.

disasm: Remove -B requirement

---

.github/workflows/release.yml
.gitignore
Makefile

By referencing the release.yml of ecapture, use GitHub Actions to release bpflbr too.

gh: Add release workflow

---

Makefile
README.md
internal/bpflbr/lbr.go

It's to avoid skipping 14 LBR entries blindly.
Because in v6.11 kernel, the LBR entries about `bpf_get_bransh_snopshot()` helper have been reduced from 7 to 2.

Skip lbr entries on demand

---

internal/bpflbr/disasm.go
internal/bpflbr/dump.go

It fails to find bpf prog func info because it does not prepare those info.
Mark `all = true` to collect all bpf progs' func info.

disasm: Fix showing bpf prog func info

---

bpf/btrace.c
go.mod
go.sum
internal/btrace/bpf_asm.go
internal/btrace/bpf_tracing.go
internal/btrace/bpf_tracing_info.go
internal/btrace/filter_fnarg.go
internal/btrace/flags.go
internal/btrace/flags_prog.go
internal/btrace/func_proto.go
internal/strx/char.go
main.go

Fixes #20 
It will be really useful to filter function argument's attribute when trace kernel functions. Afterward, it's unnecessary to trace all events of the kernel functions.
For example:
```bash
$ sudo ./btrace -k 'bpf_link_init' --filter-arg 'prog->type == BPF_PROG_TYPE_XDP'
2025/03/02 10:21:33 btrace is running..
bpf_link_init args=((struct bpf_link *)link=0xffff991e4b251e40, (enum bpf_link_type)type=BPF_LINK_TYPE_XDP, (const struct bpf_link_ops *)ops=0xffffffff89f6c700, (struct bpf_prog *)prog=0xffffa64a8008d000) retval=(void) cpu=3 process=(336879:fentry_fexit-xd)
```

fnarg: Filter function argument with simple C expression

---

bpf/btrace.c
bpf/headers/bpf_map_helpers.h
internal/btrace/btrace.go
internal/btrace/btrace_maps.go
main.go

In order to reduce some unused data in event, separate lbr data and str data from event. Afterward, in userspace, retreive lbr data and str data on demand.
Between event and lbr/str data, it uses a unique session ID to connect them:
1. Event keeps the session ID.
2. `btrace_lbrs` map uses session ID as key to store lbr data.
3. `btrace_strs` map uses session ID as key to store str data.

btrace: Introduce session ID

---

internal/btrace/flags.go
internal/btrace/flags_kfunc.go
internal/btrace/flags_prog.go
internal/btrace/kernel_functions.go
internal/btrace/kernel_functions_match.go

Fixes #17 
1. Filter by argument name only: `--kfunc '*:skb'`
2. Filter by argument name alongside its type: `--kfunc '*:sk:struct sock *'`

kfuncs: Filter kernel functions by argument

---

bpf/btrace.c
bpf/btrace.h
bpf/btrace_pkt_output.h
bpf/headers/if_ether.h
internal/btrace/bpf_asm.go
internal/btrace/bpf_get_func_arg.go
internal/btrace/bpf_spec.go
internal/btrace/bpf_tracing.go
internal/btrace/btrace.go
internal/btrace/btrace_config.go
internal/btrace/btrace_maps.go
internal/btrace/btrace_pkt.go
internal/btrace/filter_fnarg.go
internal/btrace/filter_pkt.go
internal/btrace/flags.go
internal/btrace/output_pkt.go
main.go

Fixes #32 
If `--output-pkt` and tracee has skb/xdp argument, btrace is able to output the tuple info of skb/xdp's packet data.
For example:
```bash
$ sudo ./btrace -k tcp_v4_rcv --filter-pkt 'tcp and host 1.1.1.1' --output-pkt
2025/03/07 13:05:17 btrace is running..
tcp_v4_rcv args=((struct sk_buff *)skb=0xffff991f1ef50400) retval=(int)0 cpu=6 process=(0:swapper/6)
Pkt tuple: 1.1.1.1:443 -> 192.168.241.133:42232 (TCP:SYN|ACK)
tcp_v4_rcv args=((struct sk_buff *)skb=0xffff991f1ef51d00) retval=(int)0 cpu=6 process=(0:swapper/6)
Pkt tuple: 1.1.1.1:443 -> 192.168.241.133:42232 (TCP:ACK)
tcp_v4_rcv args=((struct sk_buff *)skb=0xffff991f1ef50900) retval=(int)0 cpu=6 process=(0:swapper/6)
Pkt tuple: 1.1.1.1:443 -> 192.168.241.133:42232 (TCP:PSH|ACK)
tcp_v4_rcv args=((struct sk_buff …
```

pkt: Output packet tuple info

---

bpf/btrace.c
bpf/btrace.h
internal/btfx/types.go
internal/btrace/bpf_kfuncs.go
internal/btrace/bpf_prog_info.go
internal/btrace/bpf_tracing.go
internal/btrace/bpf_tracing_info.go
internal/btrace/btrace.go
internal/btrace/btrace_config.go
internal/btrace/func_proto.go
internal/btrace/kernel_functions.go
internal/btrace/kernel_functions_max_arg.go
internal/btrace/log.go
main.go

Fixes #29 
Since commit https://github.com/torvalds/linux/commit/473e3150e30a ("bpf, x86: allow function arguments up to 12 for TRACING")
v6.6 kernel, bpf is able to get the 6/7/8/9/10/11th argument by
`bpf_get_func_arg()` helper. Afterwards, `btrace` is able to fetch these
arguments if kernel supports it.
e.g.
```bash
$ sudo ./btrace -k 'tcp_select_*'
tcp_select_initial_window args=((const struct sock *)sk=0xffff991eeab69bc0, (int)__space=33280, (__u32)mss=0x5b4/1460, (__u32 *)rcv_wnd=0xffff991eeab6a260(0x7d78/32120), (__u32 *)window_clamp=0xffff991eeab6a244(0x7fff80/8388480), (int)wscale_ok=1, (__u8 *)rcv_wscale=0xffffa64a80a6fbc7(0x7/7), (__u32)init_rcv_wnd=0x0/0) retval=(void) cpu=5 process=(479102:curl)
```
At the same time, `btrace` has to represent the value of the argument
whose …

fnarg: Relax arg limit from 6 to 12

---

go.mod
go.sum
internal/btfx/types.go

Fixes #39 
With `mybtf.DumpBitfield()`, `btrace` is able to represent value of bitfield easily.
e.g.
```bash
$ sudo ./btrace -k 'bpf_prog_load'
bpf_prog_load args=((union bpf_attr *)attr=0xffffa64a80a9fde0, (bpfptr_t)uattr={{kernel=0x7fff215af150,user=0x7fff215af150},is_kernel=0x0}, (u32)uattr_size=0x90/144) retval=(int)4 cpu=5 process=(480818:bpftrace)
```

fnarg: Represent value of bitfield

---

internal/btrace/bpf_link.go
internal/btrace/bpf_prog.go
internal/btrace/bpf_tracing_info.go

From view of kernel bpf verifier, only these attach-types, fentry and fexit, cannot be traced by fentry/fexit. Therefore, the tracing progs with other attach-type can be traced by fentry/fexit, e.g. tp_btf.
```c
// kernel/bpf/verifier.c
int bpf_check_attach_target(struct bpf_verifier_log *log,
const struct bpf_prog *prog,
const struct bpf_prog *tgt_prog,
u32 btf_id,
struct bpf_attach_target_info *tgt_info)
{
// ...
if (prog_tracing) {
if (aux->attach_tracing_prog) {
/*
* Target program is an fentry/fexit which is already attached
* to another tracing program. More levels of nesting
* attachment are not allowed.
*/
bpf_log(log, "Cannot nest tracing program attach more than once\n");
return -EINVAL;
}
}
// ...
}
// kernel/bpf/syscall.c
static int bpf_prog_load(union bpf_attr *attr, bpfptr_t …
```

btrace: Support trace tp_btf

---

internal/btrace/output_arg.go

It's a code logic issue that produces an useless `r1 = r8` insn.
Fix it by generating `r1 = r8` when necessary.

fnarg: Reduce one insn for outputing multi args

---

README.md
go.mod
go.sum
internal/bpfsnoop/disasm.go
internal/bpfsnoop/dump.go
main.go

In [bpfsnoop/gapstone](https://github.com/bpfsnoop/gapstone), I update it to support capstone 5.0.6.
Afterwards, use [bpfsnoop/gapstone](https://github.com/bpfsnoop/gapstone) as disasm engine library.

gapstone: Bump capstone from 4.0.2 to 5.0.6

---

internal/bpfsnoop/bpfsnoop.go
internal/bpfsnoop/bpfsnoop_arg.go
internal/bpfsnoop/bpfsnoop_func.go
internal/bpfsnoop/bpfsnoop_func_data.go
internal/bpfsnoop/bpfsnoop_func_stack.go
internal/bpfsnoop/bpfsnoop_lbr.go
internal/bpfsnoop/bpfsnoop_pkt.go
internal/btfx/types.go
main.go

Separate huge `Run()` function to several functions in order to improve readability, extensibility and to fix some code logic bugs hide in it.

bpfsnoop: Refactor handling events

---

internal/bpfsnoop/disasm.go

This patch added offsets along with addresses:
gdb's `disas` has a similar output, let's implement like that:
In practice, this is useful when:
1. Mapping bpftrace's `kstack` output to source line:
```
do_sys_poll+495
__x64_sys_poll+199
x64_sys_call+8242
do_syscall_64+129
entry_SYSCALL_64_after_hwframe+120
```
The offsets are in decimal.
2. Mapping kernel panic log to source line:
```
[ 1530.421276]  __do_softirq+0xdd/0x28d
[ 1530.421284]  irq_exit_rcu+0xb9/0xf0
[ 1530.421290]  common_interrupt+0xb1/0xd0
```
The offsets are in hex.

disasm: Output insn offsets

---

internal/bpfsnoop/disasm.go
internal/bpfsnoop/dump.go
internal/bpfsnoop/func_insn.go

It's to add offset to disasm kfunc, bpf prog and insn tracing.
```bash
$ sudo ./bpfsnoop -k icmp_rcv -d -B 100
2025/04/28 07:07:07 Disassembling icmp_rcv at 0xffffffffbc615630 (100 bytes) ..
; icmp_rcv+0x0 net/ipv4/icmp.c:1180
0xffffffffbc615630 <+0/0x0>:      0f 1f 44 00 00     	nopl	(%rax, %rax)
0xffffffffbc615635 <+5/0x5>:      55                 	pushq	%rbp
; icmp_rcv+0x6 include/net/xfrm.h:1185
0xffffffffbc615636 <+6/0x6>:      31 f6              	xorl	%esi, %esi
; icmp_rcv+0x8 net/ipv4/icmp.c:1180
0xffffffffbc615638 <+8/0x8>:      48 89 e5           	movq	%rsp, %rbp
0xffffffffbc61563b <+11/0xb>:     41 57              	pushq	%r15
0xffffffffbc61563d <+13/0xd>:     41 56              	pushq	%r14
0xffffffffbc61563f <+15/0xf>:     41 55              	pushq	%r13
0xffffffffbc615641 …
```

disasm,fninsn: Unify printing insn info

---

.gitignore
Makefile
go.mod
internal/bpfsnoop/bpf_spec.go
internal/bpfsnoop/bpf_tracing.go
internal/bpfsnoop/error.go
internal/bpfsnoop/filter_arg.go
internal/cc/bpf_btf.go
internal/cc/error.go
internal/cc/eval.go
internal/cc/eval_test.go
internal/cc/expr.go
internal/cc/expr_test.go
internal/cc/insn.go
internal/cc/memory_access.go
internal/cc/memory_access_test.go
internal/cc/number.go
internal/cc/number_test.go
internal/cc/register.go
internal/cc/register_test.go
internal/cc/types.go
internal/cc/variable.go
internal/cc/variable_test.go
internal/test/test.go

It is to support complex C expression syntax in order to support complex filter condition.
The supported expression syntax includes:
1. Limited support for memory access via '.', '->', 'array[idx]',
'& (get addr)' and '* (access data of pointer)'.
2. Bitwise and '&'.
3. Bool and '&&'.
4. Ternary condition '?:'.
5. Math div '/'.
6. Bool equal '=='.
7. Bool greater than '>'.
8. Bool greater than or equal '>='.
9. Bitwise left shift '<<'.
10. Bool less than '<'.
11. Bool less than or equal '<='.
12. Unary minus '-'.
13. Math mod '%'.
14. Math multi '*'.
15. Internal constants 'true', 'false' and 'NULL'.
16. Variable from function's arguments.
17. Unary bool not '!'.
18. Bool not equal '!='.
19. Constant number.
20. Bitwise or '|'.
21. Bool or '||'.
22. Parentheses '()'.
23. Unary plus '+'. …

cc: Basic BTF-based C expression compiler for --filter-arg

---

internal/bpfsnoop/output_arg.go
internal/cc/expr.go
internal/cc/expr_test.go

It's to fix a code bug that ignore compiling result's insns when result's register is different from `asm.R3`.

fnarg: Use insns from compiling result when output arg data

---

internal/bpfsnoop/filter_arg.go
internal/bpfsnoop/output_arg.go
internal/btfx/types.go
internal/cc/bpf_btf.go
internal/cc/bpf_btf_test.go
internal/cc/bpf_core_read.go
internal/cc/bpf_core_read_test.go
internal/cc/bpf_direct_read.go
internal/cc/bpf_direct_read_test.go
internal/cc/bpf_probe_read.go
internal/cc/bpf_probe_read_test.go
internal/cc/error.go
internal/cc/eval.go
internal/cc/expr.go
internal/cc/expr_test.go
internal/cc/memory_access.go
internal/cc/memory_access_test.go
internal/test/test.go

When `bpf_rdonly_cast()` kfunc is usable on 6.x+ kernels, it will be
used to replace `bpf_probe_read_kernel()` helper.
e.g. `--filter 'skb->dev->ifindex == 2'`, bpfsnoop is able to access `dev`
and `ifindex` directly.
```bash
$ echo "bpf_rdonly_cast() version"
$ bpftool p d x n bpfsnoop_fn
bool filter_arg(__u64 * args):
; filter_arg(__u64 *args)
215: (bf) r9 = r1
216: (79) r8 = *(u64 *)(r9 +0)
217: (bf) r1 = r8
218: (b7) r2 = 1875
219: (bf) r0 = r1
220: (79) r1 = *(u64 *)(r0 +16)
221: (15) if r1 == 0x0 goto pc+8
222: (b7) r2 = 6973
223: (bf) r0 = r1
224: (61) r8 = *(u32 *)(r0 +224)
225: (67) r8 <<= 32
226: (77) r8 >>= 32
227: (55) if r8 != 0x2 goto pc+2
228: (b7) r8 = 1
229: (05) goto pc+1
230: (af) r8 ^= r8
231: (bf) r0 = r8
232: (95) exit
$ echo "bpf_probe_read_kernel() version"
$ …
```

fnarg: Use bpf_rdonly_cast() for 6.x+ kernels

---

internal/cc/bpf_core_read.go
internal/cc/bpf_core_read_test.go
internal/cc/compiler.go
internal/cc/compiler_test.go
internal/cc/expr.go
internal/cc/expr_test.go
internal/cc/memory_access_test.go

Since torvalds/linux@da7d71b ("bpf: Use KF_FASTCALL to mark kfuncs supporting fastcall contract"), `bpf_rdonly_cast()` kfunc has been marked with flag `KF_FASTCALL`, which means the unused registers R3, R4 and R5 won't be volatile after calling `bpf_rdonly_cast()` kfunc.

cc: Use fastcall bpf_rdonly_cast()

---

go.mod
go.sum
internal/bpfsnoop/addr2line.go
internal/bpfsnoop/addr2line_cache.go
internal/bpfsnoop/bpf_prog.go
internal/cc/memory_access_test.go
internal/test/test.go
makefiles/variables.mk

It's to accelerate starting `bpfsnoop`.
1. Parse vmlinux ELF file in a standalone goroutine.
2. Cache the queried addr2line entries to local file `$HOME/.cache/bpfsnoop/dbgsym.json.xz`.
1. Parse bpf prog info in standalone goroutine for each bpf prog.

disasm: Parsing vmlinux dbgsym and bpf progs info concurrently

---

Makefile
cmd/xdpcrc/xdp.c

The previous building objects were copied from `learn-by-example` repo. It would fail to build objects if remove them.
Fix then test by `./localtest --test-file ./t/xdp.txt --name 'xdp::entry_exit'`.

test: Fix building xdpcrc

---

internal/bpfsnoop/bpfsnoop_arg.go
internal/bpfsnoop/output_arg.go
internal/cc/expr.go
internal/cc/expr_func.go
internal/cc/expr_func_test.go
t/cc.txt

Instead of dumping the whole IP header and TCP/UDP header, we can dump IP addresses and TCP/UDP ports in order to catch the key info when tracing.
```bash
$ sudo ./bpfsnoop -t netif_receive_skb --filter-pkt 'host 1.1.1.1 and tcp' --output-arg 'ip42(skb->head + skb->network_header + 12)' --output-arg 'port2(skb->head + skb->transport_header)'
2025/06/26 12:34:51 bpfsnoop is running..
netif_receive_skb[tp] args=((struct sk_buff *)skb=0xffff8f75dafe0f00) cpu=6 process=(0:swapper/6)
Arg attrs: (unsigned char *)'ip42(skb->head + skb->network_header + 12)'=[1.1.1.1,192.168.241.133], (unsigned char *)'port2(skb->head + skb->transport_header)'=[443,53928]
```

fnarg: Output TCP/UDP port 

---

internal/bpfsnoop/bpfsnoop_arg.go
internal/bpfsnoop/output_arg.go
internal/cc/expr.go
internal/cc/expr_func.go
internal/cc/expr_func_test.go
internal/cc/expr_test.go
t/cc.txt

Dump kernel buffer as a slice of BTF type:
```bash
$ sudo ./bpfsnoop -k dev_xdp_install --output-arg 'slice(prog->aux->used_maps, 1)'
2025/06/26 15:10:17 bpfsnoop is running..
dev_xdp_install[ex] args=((struct net_device *)dev=0xffff8f75c2514000, (enum bpf_xdp_mode)mode=XDP_MODE_SKB, (bpf_op_t)bpf_op=0xffffffffa0f021f0(generic_xdp_install), (struct netlink_ext_ack *)extack=0xffffae0781083cf0, (u32)flags=0x0/0, (struct bpf_prog *)prog=0xffffae0780557000) retval=(int)0 cpu=4 process=(156070:xdpcrc)
Arg attrs: (struct bpf_map *)'slice(prog->aux->used_maps, 1)'=[0xffffae0780095ef0]
```

fnarg: Output slice of type

---

internal/bpfsnoop/bpf_tracepoints.go
internal/bpfsnoop/bpf_tracing.go
internal/bpfsnoop/filter_arg.go
internal/bpfsnoop/kernel_functions.go
internal/bpfsnoop/kernel_tracepoints.go
internal/bpfsnoop/output_arg.go

As for kmod, it must use the kmod's BTF spec to compile `--output-arg` and `--filter-arg` expressions, when tracing kmod's functions and tracepoints.

fnarg,tp: Compile expr using specific btf spec

---

internal/bpfsnoop/bpf_disasm.go
internal/bpfsnoop/bpf_feature.go
internal/bpfsnoop/bpf_tracing.go
internal/bpfsnoop/bpf_tracing_func.go
internal/bpfsnoop/bpf_tracing_prog.go
internal/bpfsnoop/bpfsnoop.go
internal/bpfsnoop/flags.go
internal/bpfsnoop/func_graph.go
internal/bpfsnoop/func_graph_parser.go
internal/bpfsnoop/func_graph_proto.go
internal/bpfsnoop/func_insn.go
t/massive.txt

It was broken caused by introducing per-tracee's both mode.
Meanwhile:
1. feat: Fix checking lbr.
2. Tidy code of disasm kfunc.
3. fngraph: Add hidden `--fgraph-debug` flag.
4. fngraph: Show `[traceable] mark for `--fgraph-proto`.

bpfsnoop: Fix running exit mode by default

---

internal/bpfsnoop/bpf_tracing.go
internal/bpfsnoop/disasm.go
internal/bpfsnoop/func_graph_proto.go
internal/bpfsnoop/func_proto.go
internal/bpfsnoop/kernel_btf.go

It is unable to guess the function insn count of the last entry of /proc/kallsyms, which is a bpf trampoline symbol possibly.
Then, when the last one is a bpf trampoline symbol, it cannot find its BTF info as it is not a normal kernel function builtin vmlinux.
Thereafter, as for `--fgraph-proto`, showing its function name is enough.

fngraph: Fix showing fgraph for the last entry of /proc/kallsyms

---

internal/bpfsnoop/flags.go
internal/bpfsnoop/type_proto.go

It's similar to `pahole -C`:
```bash
$ sudo ./bpfsnoop -C sock_cgroup_data
struct sock_cgroup_data {
struct cgroup *cgroup;                             /*     0     8 */
u32 classid;                                       /*     8     4 */
u16 prioidx;                                       /*    12     2 */
};
$ sudo ./bpfsnoop -C sk_buff
struct sk_buff {
union {
struct {
struct sk_buff *next;              /*     0     8 */
struct sk_buff *prev;              /*     8     8 */
union {
struct net_device *dev;    /*    16     8 */
long unsigned int dev_scratch; /*    16     8 */
};
};
...
};
struct sock *sk;                                   /*    24     8 */
union {
ktime_t tstamp;                            /*    32     8 */
u64 skb_mstamp_ns;                         /*    32     8 */
}; …
```

bpfsnoop: Show type prototype

---

Makefile
bpf/bpfsnoop_fgraph.c
internal/bpfsnoop/bpf_tracing_graph.go
internal/bpfsnoop/flags.go

Fix three minor issues:
1. makefile: Do not include `bin` dir in the final `.tar.gz` file.
2. lbr: Show line info if '(l)' is used for `-p`/`-k` and dbgsym is existing.
3. fngraph: Get the correct retval on stack by converting the `ctx` type from `unsigned long long *` to `void *`.

fngraph: Fix getting retval

---

internal/bpfsnoop/filter_arg.go
internal/bpfsnoop/flags.go
internal/bpfsnoop/output_arg.go

Sometimes, it would fail to read kernel memory using bpf_rdonly_case() kfunc:
```bash
$ sudo ./bpfsnoop -k dump_emit --output-arg 'cprm->file->f_iocb_flags'
...
297: (79) r1 = *(u64 *)(r0 +8)        ; frame1: R0=untrusted_ptr_coredump_params() R1=untrusted_ptr_file() refs=5
298: (15) if r1 == 0x0 goto pc+8      ; frame1: R1=untrusted_ptr_file() refs=5
299: (b7) r2 = 649                    ; frame1: R2_w=649 refs=5
300: (85) call bpf_rdonly_cast#41126          ; frame1: R0_w=untrusted_ptr_file() refs=5
301: (61) r7 = *(u32 *)(r0 +0)
cannot access ptr member next with moff 0 in struct callback_head with off 0 size 4
processed 190 insns (limit 1000000) max_states_per_insn 0 total_states 14 peak_states 14 mark_read 11
```
To address this, it is able to read kernel memory using …

cc: Add hidden -P to read kernel memory using bpf_probe_read_kernel() 

---

bpf/bpfsnoop.c
bpf/bpfsnoop_fgraph.c
bpf/bpfsnoop_stack.h
internal/bpfsnoop/bpfsnoop_sess.go

Since patch [bpf: Support private stack for bpf progs](https://lore.kernel.org/all/20241112163902.2223011-1-yonghong.song@linux.dev/)
(v6.13 kernel), it is unable to unwinding stack from current prog's fp,
because the true fp has been hidden from private stack.
However, the `ctx` of current prog is a pointer of trampoline's stack.
So, it is able to get trampoline's fp using `ctx`, as it knows args
number and knows retval is on trampoline's stack or not.
Check the trampoline's stack layout in `bpfsnoop_stack.h` for more
details.

fngraph: Fix getting fp of trampoline 
